project:
  type: website
  output-dir: docs

website:
  title: "Connor Wang"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Data Viz
        menu:
          - text: "Bob's Burgers"
            href: dataviz/bobsburgers.qmd
          - text: "Horror Movies"
            href: dataviz/horrormovies.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: full

editor: visual

